export const ICONS = {
    home: require('assets/images/tabIcon/home.png'),
    home_focused: require('assets/images/tabIcon/home_blue.png'),
    customBox: require('assets/images/tabIcon/custom.png'),
    customBox_focused: require('assets/images/tabIcon/custom_blue.png'),
    storage: require('assets/images/tabIcon/storage.png'),
    storage_focused: require('assets/images/tabIcon/storage_blue.png'),
    myPage: require('assets/images/tabIcon/user.png'),
    myPage_focused: require('assets/images/tabIcon/user_blue.png'),
    info: require('assets/images/info.png'),
    downArrow: require('assets/images/down_arrow.png'),
    upArrow: require('assets/images/up_arrow.png'),
    leftArrow: require('assets/images/left_arrow.png'),
    cart: require('assets/images/cart.png'),
    search: require('assets/images/search.png'),
    xCircle: require('assets/images/x_circle.png'),
    minus: require('assets/images/btn_subtract.png'),
    plus: require('assets/images/btn_add.png'),
    checkBox_checked: require('assets/images/btn_chkbox_chkd.png'),
    checkBox_unchecked: require('assets/images/btn_chkbox.png'),
    x: require('assets/images/x.png')
}